baseURL: https://www.mcstaralliance.com
languageCode: zh-cn/
title: 星域 Blog
theme: PaperMod
params:
  homeInfoParams:
        Title: "欢迎来到星域博客。"
        Content: >


  socialIcons:
        - name: github
          url: "https://github.com/mcstaralliance"
        - name: Rss
          url: "index.xml"
  editPost:
        URL: "https://github.com/mcstaralliance/Blog/tree/main/content"
        Text: "Suggest Changes"
        appendFilePath: true

languages:
    en:
        languageName: "English"
        weight: 1
        taxonomies:
          category: categories
          tag: tags
          series: series
        menu:
            main:
                - name: 归档
                  url: archives
                  weight: 5
                - name: 搜索
                  url: search/
                  weight: 10
                - name: 标签
                  url: tags/
                  weight: 10
                - name: Celestia Skin（皮肤站）
                  url: https://skin.mcstaralliance.com
